name: mantenedor-salaventas
services:
  mantenedorsalaventas:
    container_name: mantenedor-salaventas
    image: mantenedor-salaventas:v1
    networks:
      - dicrep

networks:
  dicrep:
    external: true